### ISSUE TITLE
这里为什么要单独实现heartbeat

### ISSUE THREAD

**Issue by StarMX** [openatx/atxserver2-android-provider#1]
原有atx-agent在python atxserver2版本里没看到有接收heartbeat实现。
看了下go版的实现 
 HMACSHA256(( Request.from["timestamp"] +‘:’ + Request.from["identifier"]),password)==request.from["messageMAC"]
password为:hello kitty

**Comment by StarMX** [comment]
额，貌似弄明白了 为了"platform": "android"

**Comment by StarMX** [comment]
顺便啰嗦一句 tcpproxy.js 没有重连机制

**Comment by codeskyblue** [comment]
tcpproxy.js 就是一个tcp转发工具，要啥重连
另外heartbeat 现在改成了websocket

**Comment by codeskyblue** [comment]
等这个provider没啥要改的了，atx-agent以后也会跟着一起改。
