### ISSUE TITLE
部署完远程无法看到手机屏幕

### ISSUE THREAD

**Issue by ulwxfjy** [openatx/atxserver2-android-provider#11]
**Warning**

These issues are not tracked. Please create new issues in the main _atxserver2_
repository: https://github.com/openatx/atxserver2/issues/new

![image](https://user-images.githubusercontent.com/17308602/57342764-0fb1d080-7173-11e9-9a5d-4b8b34e92b8d.png)

DeviceEvent(present=True, serial='98895a3447564a4a48', status='device')
[I 190508 09:22:15 device:56] Init device: 98895a3447564a4a48
[D 190508 09:22:15 device:79] [98895a3447564a4a48] sdk: 26, abi: arm64-v8a, abis: ['arm64-v8a', 'armeabi-v7a', 'armeabi']
[D 190508 09:22:15 device:100] [98895a3447564a4a48] use atx-agent: atx-agent-armv7
[D 190508 09:22:16 device:124] [98895a3447564a4a48] already installed vendor/WhatsInput_v1.0_apkpure.com.apk
[D 190508 09:22:16 device:124] [98895a3447564a4a48] already installed vendor/app-uiautomator.apk
[D 190508 09:22:16 device:124] [98895a3447564a4a48] already installed vendor/app-uiautomator-test.apk
[D 190508 09:22:16 device:134] [98895a3447564a4a48] forward atx-agent
[D 190508 09:22:16 device:178] [98895a3447564a4a48] tcpproxy.js start *:20000 -> 20010
[D 190508 09:22:16 device:178] [98895a3447564a4a48] tcpproxy.js start *:20001 -> 20012
[D 190508 09:22:16 device:139] [98895a3447564a4a48] adbkit start, port 20002
[I 190508 09:22:17 main:254] Device:98895a3447564a4a48 is ready
[D 190508 09:22:17 main:228] DeviceEvent(present=True, serial='f61cfec3', status='device')
[I 190508 09:22:17 device:56] Init device: f61cfec3
[D 190508 09:22:17 device:79] [f61cfec3] sdk: 25, abi: armeabi-v7a, abis: ['armeabi-v7a', 'armeabi']
[D 190508 09:22:17 device:100] [f61cfec3] use atx-agent: atx-agent-armv7
[D 190508 09:22:18 device:124] [f61cfec3] already installed vendor/WhatsInput_v1.0_apkpure.com.apk
[D 190508 09:22:18 device:124] [f61cfec3] already installed vendor/app-uiautomator.apk
[D 190508 09:22:18 device:124] [f61cfec3] already installed vendor/app-uiautomator-test.apk
[D 190508 09:22:18 device:134] [f61cfec3] forward atx-agent
[D 190508 09:22:18 heartbeat:93] websocket send: {'udid': '98895a3447564a4a48', 'platform': 'android', 'colding': False, 'provider': {'atxAgentAddress': '192.168.5.124:20000', 'remoteConnectAddress': '192.168.5.124:20002', 'whatsInputAddress': '192.168.5.124:20001'}, 'properties': {'serial': '98895a3447564a4a48', 'brand': 'samsung', 'version': '8.0.0', 'model': 'SM-G9500', 'name': '三星 Galaxy S8'}, 'command': 'update'}
[D 190508 09:22:18 device:178] [f61cfec3] tcpproxy.js start *:20003 -> 20005
[D 190508 09:22:18 device:178] [f61cfec3] tcpproxy.js start *:20004 -> 20007
[D 190508 09:22:18 device:139] [f61cfec3] adbkit start, port 20006
[I 190508 09:22:21 main:254] Device:f61cfec3 is ready
[D 190508 09:22:21 heartbeat:93] websocket send: {'udid': 'f61cfec3', 'platform': 'android', 'colding': False, 'provider': {'atxAgentAddress': '192.168.5.124:20003', 'remoteConnectAddress': '192.168.5.124:20006', 'whatsInputAddress': '192.168.5.124:20004'}, 'properties': {'serial': 'f61cfec3', 'brand': 'Xiaomi', 'version': '7.1.2', 'model': 'MI 4LTE', 'name': '小米 4 '}, 'command': 'update'}
三星S8官方系统，小米4刷的魔趣系统

**Comment by codeskyblue** [comment]
多谢反馈，但请将issue提到 atxserver2项目中
