### ISSUE TITLE
执行 python main.py  --server localhost:4000时，提示   No module named 'apkutils'

### ISSUE THREAD

**Issue by wufan0115** [openatx/atxserver2-android-provider#12]
**Warning**

These issues are not tracked. Please create new issues in the main _atxserver2_
repository: https://github.com/openatx/atxserver2/issues/new

![image](https://user-images.githubusercontent.com/22274031/57500698-ee89e500-7316-11e9-962b-6d719dd918ea.png)

**Comment by codeskyblue** [comment]
安装缺失的库就好了
