### ISSUE TITLE
atxserver2-android-providers的adb是在哪里呢？它的版本跟我服务器的adb版本不一致，显示不匹配

### ISSUE THREAD

**Issue by RealMay** [openatx/atxserver2-android-provider#19]
**Warning**

These issues are not tracked. Please create new issues in the main _atxserver2_
repository: https://github.com/openatx/atxserver2/issues/new

**Comment by codeskyblue** [comment]
重新看了下代码，atxserver2并不自带adb，只有docker镜像中会包含一个1.0.40版本的adb
