### ISSUE TITLE
git lfs pull 提示This repository is over its data quota.

### ISSUE THREAD

**Issue by PokerDealer** [openatx/atxserver2-android-provider#21]
![image](https://user-images.githubusercontent.com/43975808/64155595-aa8e9300-ce65-11e9-9d2e-9cb9653a3087.png)

**Comment by hutuxiansheng** [comment]
遇到一样的问题

**Comment by cai-git** [comment]
the same

**Comment by private33** [comment]
please help, i've got the same issue

**Comment by testerwang11** [comment]
欠费，大文件无法下载
