### ISSUE TITLE
git lfs pull 失败

### ISSUE THREAD

**Issue by joelai** [openatx/atxserver2-android-provider#23]
报错如下

batch response: This repository is over its data quota. Purchase more data packs to restore access.                               
error: failed to fetch some objects from 'https://github.com/openatx/atxserver2-android-provider.git/info/lfs'

**Comment by hnlylmlzh** [comment]
我也是。。

**Comment by lixintester** [comment]
遇到同样的问题。。。

**Comment by testerwang11** [comment]
欠费，大文件无法下载
