### ISSUE TITLE
python3 main.py --server localhost:4000后报错

### ISSUE THREAD

**Issue by lyp0129** [openatx/atxserver2-android-provider#25]
python3 main.py --server localhost:4000后报错

 File "/Users/luyunpeng/Downloads/myworkspace/atx2/atxserver2-android-provider/device.py", line 136, in _init_apks
    whatsinput_apk_path = get_whatsinput_apk()
NameError: name 'get_whatsinput_apk' is not defined

**Comment by private33** [comment]
i've been facing same issue.
![image](https://user-images.githubusercontent.com/26137277/65141213-5e814800-da3a-11e9-804b-bcdd28689c3b.png)

**Comment by codeskyblue** [comment]
fixed
