### ISSUE TITLE
error 'NoneType' object has no attribute 'package_name'

### ISSUE THREAD

**Issue by ruberzhu** [openatx/atxserver2-android-provider#3]
Traceback (most recent call last):
  File "main.py", line 124, in _install_apk
    info = self._device.package_info(m.package_name)
AttributeError: 'NoneType' object has no attribute 'package_name'
[W 190326 14:44:00 main:133] [ce10171a3a96042f0c7e] Install apk vendor/WhatsInput_v1.0_apkpure.com.apk error 'NoneType' object has no attribute 'package_name'

**Comment by codeskyblue** [comment]
update代码  并  pip install -r requirements.txt

**Comment by ruberzhu** [comment]
> update代码 并 pip install -r requirements.txt

好的。谢谢及时解决。
另外问个小问题，wifi远程链接手机可否支持。如果没有时间开发，可否稍作指点，作为参考？

**Comment by ruberzhu** [comment]
> update代码 并 pip install -r requirements.txt
还是有点问题
----
[root@localhost atxserver2-android-provider]$ pip3  install -r requirements.txt
Requirement already satisfied: logzero==1.5.* in /usr/Python-3.7.2/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: adbutils==0.2.* in /usr/Python-3.7.2/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: tornado in /usr/Python-3.7.2/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (4.5.3)
Requirement already satisfied: requests in /usr/Python-3.7.2/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.21.0)
Requirement already satisfied: apkutils-patch==0.5.* in /usr/Python-3.7.2/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.5.4)
Requirement already satisfied: whichcraft in /usr/Python-3.7.2/lib/python3.7/site-packages (from adbutils==0.2.*->-r requirements.txt (line 2)) (0.5.2)
Requirement already satisfied: six in /usr/Python-3.7.2/lib/python3.7/site-packages (from adbutils==0.2.*->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/Python-3.7.2/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/Python-3.7.2/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/Python-3.7.2/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/Python-3.7.2/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (2018.11.29)
Requirement already satisfied: pyelftools in /usr/Python-3.7.2/lib/python3.7/site-packages (from apkutils-patch==0.5.*->-r requirements.txt (line 5)) (0.25)
Requirement already satisfied: cigam in /usr/Python-3.7.2/lib/python3.7/site-packages (from apkutils-patch==0.5.*->-r requirements.txt (line 5)) (0.0.3)
Requirement already satisfied: xmltodict in /usr/Python-3.7.2/lib/python3.7/site-packages (from apkutils-patch==0.5.*->-r requirements.txt (line 5)) (0.12.0)

-----
[D 190326 19:48:10 main:168] DeviceEvent(present=True, serial='5LM7N16406014587', status='device')
[I 190326 19:48:10 device:56] Init device: 5LM7N16406014587
--Status init
[D 190326 19:48:10 device:76] [5LM7N16406014587] sdk: 26, abi: arm64-v8a, abis: ['arm64-v8a', 'armeabi-v7a', 'armeabi']
[D 190326 19:48:11 device:97] [5LM7N16406014587] use atx-agent: atx-agent-armv7
Traceback (most recent call last):
  File "/home/lianjia/mobile/atxserver2-android-provider/device.py", line 119, in _install_apk
    info = self._device.package_info(m.package_name)
AttributeError: 'NoneType' object has no attribute 'package_name'
[W 190326 19:48:11 device:128] [5LM7N16406014587] Install apk vendor/WhatsInput_v1.0_apkpure.com.apk error 'NoneType' object has no attribute 'package_name'
Traceback (most recent call last):
  File "/home/lianjia/mobile/atxserver2-android-provider/device.py", line 119, in _install_apk
    info = self._device.package_info(m.package_name)
AttributeError: 'NoneType' object has no attribute 'package_name'
[W 190326 19:48:11 device:128] [5LM7N16406014587] Install apk vendor/app-uiautomator.apk error 'NoneType' object has no attribute 'package_name'
Traceback (most recent call last):
  File "/home/lianjia/mobile/atxserver2-android-provider/device.py", line 119, in _install_apk
    info = self._device.package_info(m.package_name)
AttributeError: 'NoneType' object has no attribute 'package_name'
[W 190326 19:48:11 device:128] [5LM7N16406014587] Install apk vendor/app-uiautomator-test.apk error 'NoneType' object has no attribute 'package_name'
[D 190326 19:48:11 device:131] [5LM7N16406014587] forward atx-agent

**Comment by codeskyblue** [comment]
apkutils-patch 这个库单独更新下试试 pip install -U apkutils-patch


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
>> update代码 并 pip install -r requirements.txt ...

@ruberzhu 另外wifi 连接，需要改atx-agent 需要等协议稳定了才行

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ruberzhu** [comment]
> apkutils-patch 这个库单独更新下试试 pip install -U apkutils-patch
> 
> Sent with [GitHawk](http://githawk.com)

新的问题

Traceback (most recent call last):
  File "/home/lianjia/mobile/atxserver2-android-provider/device.py", line 121, in _install_apk
    if info and m.version_code == info['version_code'] and m.version_name == info['version_name']:
KeyError: 'version_code'

**Comment by codeskyblue** [comment]
adbutils 也更新下

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
咋样了？

**Comment by ruberzhu** [comment]
可以了。感谢及时修复。比较期待wifi连接。另外有些ios问题，一会移步ios项目提下

**Comment by ruberzhu** [comment]
mac系统报如下：

Traceback (most recent call last):
  File "main.py", line 248, in <module>
    IOLoop.current().run_sync(async_main)
  File "/usr/local/lib/python3.7/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "main.py", line 229, in async_main
    await device_watch()
  File "main.py", line 178, in device_watch
    await device.init()
  File "/Users/r/Documents/code/app/atxserver2-android-provider/device.py", line 59, in init
    self._init_binaries()
  File "/Users/r/Documents/code/app/atxserver2-android-provider/device.py", line 80, in _init_binaries
    "/minicap.so", "/data/local/tmp/minicap.so", 0o644)
  File "/Users/r/Documents/code/app/atxserver2-android-provider/device.py", line 104, in _push_stf
    with zipfile.ZipFile(zipfile_path) as z:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by ruberzhu** [comment]
另外一个问题，在执行远程控制过程中，进行monkey测试时，monkey报错，如下：

ava.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@46aa3d5already registered!
	at android.os.Parcel.createException(Parcel.java:1961)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:409)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:399)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:97)
	at android.app.UiAutomation.connect(UiAutomation.java:238)
	at android.app.UiAutomation.connect(UiAutomation.java:214)

怀疑二者在使用UiAutomation时有冲突，有无解药？

**Comment by codeskyblue** [comment]
zip合适不对，应该是git lfs 的问题

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
uiautomator是独占资源，只能停掉其中一个。d.service("uiautomator").stop() 可以停掉atx的

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
