### ISSUE TITLE
执行python3 main.py --server localhost:4000报错

### ISSUE THREAD

**Issue by loneyao** [openatx/atxserver2-android-provider#4]
Last login: Wed Mar 27 16:18:35 on ttys002
Mac-mini-4:~ mac$ cd /Users/mac/atxserver2-android-provider 
Mac-mini-4:atxserver2-android-provider mac$ python3 main.py --server localhost:4000
[I 190327 16:21:10 main:222] ProviderURL: http://10.1.8.194:3500
[W 190327 16:21:10 heartbeat:113] WS connect error: [Errno 61] Connection refused, reconnect after 2s
[W 190327 16:21:12 heartbeat:113] WS connect error: [Errno 61] Connection refused, reconnect after 3s
[W 190327 16:21:15 heartbeat:113] WS connect error: [Errno 61] Connection refused, reconnect after 4s
[W 190327 16:21:19 heartbeat:113] WS connect error: [Errno 61] Connection refused, reconnect after 5s
[W 190327 16:21:24 heartbeat:113] WS connect error: [Errno 61] Connection refused, reconnect after 6s
[W 190327 16:21:30 heartbeat:113] WS connect error: [Errno 61] Connection refused, reconnect after 7s

**Comment by codeskyblue** [comment]
atxserver2没启动，当然这样啦

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 1070148808** [comment]
> atxserver2没启动，当然这样啦
> 
> Sent with [GitHawk](http://githawk.com)

how to start atxserver2 ??? sorry

**Comment by 1070148808** [comment]
> > atxserver2没启动，当然这样啦
> > Sent with [GitHawk](http://githawk.com)
> 
> how to start atxserver2 ??? sorry

i got it
