### ISSUE TITLE
atxserver2-android-provider过滤掉了串号的IP地址的设备

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/atxserver2-android-provider#5]
1. 某些root的设备，使用adb connect 设备IP，adb devices执行命令后，显示如10.0.0.2:5555 device。
2.当连接这些设备后，atxserver2-android-provider会过滤掉串号为IP地址的设备，其实应当过滤掉如10.0.0.2:5555 offline的设备。
3.对应代码的判断 if re.match(r"(\d+)\.(\d+)\.(\d+)\.(\d+):(\d+)", event.serial)，此处可能需要优化一下，当前我屏蔽了此处代码判断，设备可以init成功，并且成功连接到atxserver2

**Comment by codeskyblue** [comment]
默认是屏蔽的，不过可以通过命令行选项 `--allow-remote` 允许这类ip地址的设备。文档需要说明下。

**Comment by codeskyblue** [comment]
已添加
