### ISSUE TITLE
2部手机usb连接报错

### ISSUE THREAD

**Issue by zhangge3992513** [openatx/atxserver2-android-provider#6]
Hi, 这是一个很棒的项目.
我在使用过程中报错了,
第1部手机usb连接正常,
第2部手机连接就报错:
https://github.com/openatx/atxserver2-android-provider/blob/master/asyncadb.py#L60
报错: `asyncadb.ADBError: unknow host service`.
然后我执行命令 `adb forwad --list` 打印出 `error: unknown host service`

**Comment by codeskyblue** [comment]
额，你执行 `adb forward --list` 返回 unknown host service?

**Comment by codeskyblue** [comment]
你先暂时换成 adb 1.0.39 临时解决下

**Comment by black-cmd** [comment]
后来通过替换adb版本解决了么?  我这边替换了还未生效

**Comment by black-cmd** [comment]
官网下载最新版本  Android Debug Bridge version 1.0.41,问题得到解决
