### ISSUE TITLE
怎么能脱离usb连接设备呢?

### ISSUE THREAD

**Issue by xinxi1990** [openatx/atxserver2-android-provider#7]
**Warning**

These issues are not tracked. Please create new issues in the main _atxserver2_
repository: https://github.com/openatx/atxserver2/issues/new

**Comment by codeskyblue** [comment]
开了个分支在弄，还没搞完
https://github.com/openatx/atx-agent/tree/atxserver2

**Comment by codeskyblue** [comment]
issue关掉了，这个会在 atxserver2项目中的issue中更新的 https://github.com/openatx/atxserver2/issues/1
